name: üìù Build Docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - 'src/docs/**'
permissions:
  contents: read
jobs:
  build-docs:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: üìÇ Checkout Repo
        uses: actions/checkout@v4

      - name: üìù Build Docs with Dagger
        uses: dagger/dagger-for-github@8.0.0
        env:
          GITHUB_CONTEXT_JSON: ${{ toJSON(github) }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest
          verb: call
          module: github.com/twocaretcat/actions-sandbox-2/dagger
          args: |2-
              --source-dir='./' \
              --default-templates-dir='https://github.com/twocaretcat/actions-sandbox-2.git#main:templates' \
              --token='env://TOKEN' \
            with-nunjucks-context \
              --data-file='project-metadata.json' \
              --output-key='project' \
            with-nunjucks-context-from-github \
              --github-context-secret='env://GITHUB_CONTEXT_JSON' \
            build-docs \
              --with-paths='src/docs/CODE_OF_CONDUCT.md.njk:docs/CODE_OF_CONDUCT.md' \
              --with-paths='src/docs/CODE_OF_CONDUCT.md.njk:docs/CODE_OF_CONDUCT_2.md' \
              --with-paths='src/docs/CODE_OF_CONDUCT.md.njk:docs/CODE_OF_CONDUCT_3.md' \
              --with-paths='src/docs/CODE_OF_CONDUCT.md.njk:docs/CODE_OF_CONDUCT_4.md' \
            export \
              --path='./'
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: üì§ Commit Changes
        uses: EndBug/add-and-commit@v9
        if: ${{ !env.ACT }}
        with:
          add: |
            ./LICENSE
            :(glob)**/*.md
          committer_name: dojomentation[bot]
          committer_email: dojomentation-bot.twocaretcat@users.noreply.github.com
          message: 'üìù build docs for ${{ github.sha }} [skip ci]'
